blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/bmf-san/gohan/discussions
    about: For general questions or discussions, please use GitHub Discussions.
